### ISSUE TITLE
"'PI_GroundServices' failed to load" in PythonInterfaceLog.txt

### ISSUE THREAD

**Issue by LinusGeffarth** [joanpc/GroundServices#2]
On my Mac, I followed the instructions to install everything a couple times. I have installed Python 3.5 but the PythonInterface plugin in X-Plane 10 is not able to install the ground services.
Did some research, did not find anything useful.

**Comment by joanpc** [comment]
Hi Linus,

You should install Python 2.7. Let me know i you need further help.

**Comment by LinusGeffarth** [comment]
Hey Joan,
 I had Python 2.7 installed but it did not work  so I updated python to 3.5 as suggested in a forum.

**Comment by joanpc** [comment]
Did you try any other python script? Is there any working?

**Comment by LinusGeffarth** [comment]
Nope, I did not. I'll give that a shot later today.
Thanks for assisting :)

**Comment by LinusGeffarth** [comment]
Ok, so I tried your weather plugin, that did not work either. Same error message :/

**Comment by joanpc** [comment]
Hi Linus, there's a know bug on the xplane Python interface that is unable to load a script if there's a "weird" character on the path like an apostrophe. Check that. It will be useful if you send-me your PythonInterfaceLog.txt to xplane at joanpc.com

**Comment by LinusGeffarth** [comment]
[PythonInterfaceLog.txt](https://github.com/joanpc/GroundServices/files/124930/PythonInterfaceLog.txt)
This is the log. There actually is an apostrophe, but it is in my SSD's name so I won't be able to change that w/o formatting it, right?

**Comment by joanpc** [comment]
This should be the problem, as you can see on the log the plugin is using the full path to access the files

```
Using path below for script path
/Volumes/Linus' SSD/Users/Games/Desktop/X-Plane 10/Resources/plugins/PythonScripts
```

You can change its name by just right clicking the drive on the devices list on the left sidebar on finder. If it doesn't appear go to finder preferences, sidebar, hardisks should be checked. Then you should reboot an enjoy the plugins (i hope).

Let me know anyway :)

**Comment by LinusGeffarth** [comment]
Great! Thank you so much. (For your help & the great tool)
